### ISSUE TITLE
LDAP sync

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-authbackend-ldap#3]
Hello there!

We have a little problem regarding this component.

We have the authentication and authorization delegated on LDAP.

When a user is added to one group which allows access to Kibana and the user logs into Kibana using these permissions and after that we remove that user from the LDAP group... the user still has login permission to Kibana with the old role.

Is there any way to re-sync the LDAP information into SearchGuard? How can we configure the sync period?

In addition, if we delete the user from the LDAP, he still has access to Kibana. Maybe there is a cache somewhere...

Thanks,
Best regards

**Comment by jochenkressin** [comment]
That's due to the internal user cache in Search Guard. At the moment, you cannot set the cache timeout manually, it's set 1 hour. We'll think about making this configurable in future releases.

As a workaround, you can use sgadmin to clear the cache manually. For that, use the -rl / --reload switch. You do not need to specify any configuration directory etc., the switch simply reloads the current config and clears the cache.

**Comment by alesnav** [comment]
Ok, it works this way.

Thanks for your incredibly fast help!

**Comment by floragunn** [comment]
related to https://github.com/floragunncom/search-guard-rest-api/issues/5
